spring.application.name=crm-backend
# Puerto de la aplicación
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/crm_backend
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true

spring.sql.init.mode=never

# Logging
logging.level.org.springframework=INFO
logging.level.com.startupcrm=DEBUG

server.error.include-stacktrace=never
server.error.include-message=never

#usar configuracion local
# spring.profiles.active=dev
#Este debe ir en application.properties
#pero para evitar conclictos es mejor activar dev con
# En local (IntelliJ / terminal)
#-Dspring.profiles.active=dev


#spring.jpa.hibernate.ddl-auto=update

#puebla en automatico la BD, ejecutando data.sql
#spring.sql.init.mode=always

#evita errores si Hibernate no ha creado las tablas
#spring.jpa.defer-datasource-initialization=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



